### ISSUE TITLE
[기능개선제안] 날짜 및 시간 생성 오류, 복사 완료 알림 메세지 지속 시간 설정

### ISSUE THREAD

**Issue by subincdev** [qorlgns1/commit-date-change#1]
## 제안할사항
날짜 및 시간 생성 오류, 복사 완료 알림 메세지 지속 시간 설정
## 제안한 이유
날짜 및 시간 생성 오류, 복사 완료 알림 메세지들이 사라지지않아, 사용자의 입장에서 기능을 사용할 때 혼동이 생길 수 있을 것 같습니다. 
메세지들의 지속시간이 설정되었으면 좋겠습니다. 
## 추가적으로 논의할 사항
없음
## Pull Request(PR)를 통해 수정할 의향이 있습니까?
네

**Comment by qorlgns1** [comment]
좋은 아이디어인것 같습니다!
